name: Index Page Update

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: s-weigand/setup-conda@v1
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python environment
        run: conda install -y numpy
      - name: update research
        run: 
            python get_research.py index.html research.html
      - name: update news
        run: 
            python get_news.py index.html news.html
      - uses: EndBug/add-and-commit@v9 
        with:
          add: '.'
          author_name: Michael Wray
          author_email: michael.wray@bristol.ac.uk
          commit: ''
          cwd: '.'
          message: 'Updates index page'
